PreCommit:
  RuboCop:
    enabled: true
    command: ['standardrb']
    required: true
  Standard:
    enabled: true
    command: ['pnpm', 'exec', 'standard']
    required_executable: false
    required: true
    exclude:
      - 'vendor/**/*.js'
  ErbLint:
    enabled: true
    required: true